name: Run Selenium Script

on:
  workflow_dispatch:  # Permite rodar manualmente
  schedule:
    - cron: "0 * * * *"  # Roda a cada hora (modifique se necessário)

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script Selenium
        run: python main.py
