name: Run Selenium Script

on:
  push:
    branches:
      - main  # Você pode alterar para o nome da sua branch principal
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Usando uma máquina virtual do Ubuntu

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Define a versão do Python que você quer usar

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Python script
      run: |
        python seu_script.py  # Nome do seu script Python

